### ISSUE TITLE
RFC: single-repo vs. multi-repo

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#14]
I'm honestly on the fence on this one, but it's about time to figure it out: do we want to keep openstates/openstates a single repo, or split it out into state-repos going forward?

Arguments:

Single Repo:
* easier to manage, check-out, etc.
* keep entire history entact without crazy git-fu
* one place for tickets
* simplifies deployment
* openstates common tools don't need own repo (but maybe they should anyway?)

Multi Repo:
* easier to see at a glance what issues exist in specific states
* (neutral) can use waffle.io/openstates/openstates or similar to combine repos for super-view
* can delegate commit authority more granularly
 
(I'd love to hear people's thoughts, feel free to use this as a discussion.  I'll make an executive decision when we start work on pupa-ized scrapers in earnest.)

**Comment by jamesturk** [comment]
(I'd love to hear people's thoughts, feel free to use this as a discussion.  I'll make an executive decision when we start work on pupa in earnest.)

**Comment by jamesturk** [comment]
👍 this comment for multi-repo

**Comment by showerst** [comment]
A few additional thoughts in favor of single-repo:

1. I think maintaining naming standards for bug-filing (STATE: bug or tagging) equals out the first advantage of multi-repo. 
1. Single repo feels like it will make openstates more accessible for new people, or anyone who's working on a scraper and wants to know how we do (X) in another state.
1. On the (admittedly few) days where we do work on multiple states in the same day, jumping around between repos sounds like a real pain.

**Comment by jamesturk** [comment]
seems pretty one-sided, one-repo wins
