### ISSUE TITLE
Migrate Scrapers to Pupa

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#15]
- [x] write pupa JSON->billy converter
    - [x] bills
    - [x] votes
    - [x] legislators
    - [x] committees
    - [x] events
- [x] create way to run pupa scrapers alongside billy scrapers from main repo
- [x] flake8 all pupa scrapers (add travis hook for this)
- [ ] one-by-one update task runner to run pupa-ized scrapers from that branch
- [ ] once we reach critical mass (15-20?) also start ingesting pupa JSON into an OCD DB

**Comment by jamesturk** [comment]
Since openstates/pupa-fl is almost ready and a few more pupa branches are coming into being, I want to discuss the second point here about the long-lived pupa branch.

Curious what flow people would prefer for these going forward:

Plan A: long lived 'pupa' branch
- uses 'openstates/{state}' directory for new scrapers
- presumably we'd delete the old billy scraper from 'openstates/{state}' in the master branch so that people don't accidentally work on it
   
Plan B: start merging these in to master as they're completed
- using openstates/{state} directories, so old scrapers are replaced completely (still of course accessible via Git history)
- people would have to know (not hard to tell) if they were looking at a pupa or billy scraper as they'd live side-by-side

Plan C: merge these into master as completed, but use new directory
- billy scrapers would live in openstates/{state} as they do  now
- pupa scrapers would live in scrapers/{state}. 
- when scrapers/fl is merged we'd delete openstates/fl

I'm sort of favoring plan C as it is the most clear where things live, etc.  Everyone can look at master for the currently running scrapers, but can easily distinguish which scrapers are pupa-ized.

Thoughts?  

@mileswwatkins @fgregg @showerst @jmcarp

**Comment by fgregg** [comment]
Based on my work on Illinois, I prefer options A or B. I'm finding that I can make pretty incremental modifications to the billy scrapers to turn them into pupa scrapers. As such, I think it will be nice to have continuous commit history.

**Comment by mileswwatkins** [comment]
Hmm, what's going to be the easiest to understand for devs just starting with the project? Similarly, what's going to be the easiest to make work in Docker, if it has to be able to easily run both Pupa _and_ Billy scrapes?

I'm really unsure as to which is the most intuitive. Originally I liked A, but since we'll stop supporting a Billy scraper once it's ported, having Pupa "hidden" in a separate branch won't have benefits. I guess B is the best IMO, if accompanied by a Billy hotfix to recognize when someone's trying to run it on a Pupa scraper, and telling them where to find Pupa quickstart docs instead?

**Comment by jamesturk** [comment]
Yeah, I started to realize ease of figuring out what is going on in a given state is a real strike against Option A IMO.

If they live in the same branch there'll be two dockerfiles and docker-compose will call the newer one something like 'scrape' so invocation is like ``docker-compose run scrape fl people --fast``

**Comment by jamesturk** [comment]
If anyone wants to check out what Option B would look like here's a pass at it:

https://github.com/openstates/openstates/pull/1399

**Comment by jamesturk** [comment]
https://github.com/openstates/openstates/issues/1442 is the issue to track now
