### ISSUE TITLE
Sync up w/ NIMSP ids?

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#16]
In the past we had nimsp_candidate_ids but they took a huge amount of manual work.

If we can come up with a semi-automated system we could look at restoring this, if not we may need to drop this ID going forward.

**Comment by jonConerly** [comment]
I've tried to use their API a couple of times for another project(tried again before writing this), it does not appear to be working.  I can look up my representative and see the data on their site, but the API calls(exported using the official method), return blank documents.  Even if OS gets some sort of internal connection to the data, it appears that most of the maintenance will have to fall on the core members due no one else being able to test/see the data.

**Comment by jamesturk** [comment]
Ah good to know, that'll be of limited use then :/ 

I'll check w/ them on the status of their API

**Comment by jamesturk** [comment]
going to consider this dead for now, we can always look at future feature requests if there is a need and a way to go forward
