### ISSUE TITLE
future of manual data quality tools

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#17]
I've been thinking about what a collaborative approach to data quality issues looks like, something that will be increasingly important w/ a more decentralized approach to running the project. (at Sunlight we were able to have a full time intern dedicated to this so there was less demand for a tool that would let people suggest changes)

We also often get questions like "where did X come from?" and we don't have a good answer, some intern entered it a few years ago and we never took another look at it.  

Another similar question is "can I submit manual changes for Y" and we have to turn those requests away too.  This is also an issue when people develop locally as their local copy will never truly match our data without these edits.

It'd be great if we had a way to:
- accept proposed edits
- see what edits had been made in the past (bonus: be able to roll them back)
- let people apply the same edits we have applied to their own data

The more I thought about this the more I realized we already have a tool that is good at a lot of this, Git.

Imagine a repository 'manual_edits' that is essentially a big repo of JSON files:

fix_ak_first_name.json
```
{'object': 'AKL0000001', 'action': 'update-values', 'values': 
    {'first_name': {'old': 'Jamse, 'new': 'James'}}
}
```

fix_ri_party.json
```
{'objects': 'AKL*', 'action': 'update-values', 'values': 
    {'party': {'old': '(D)', 'new': 'Democratic'}}
  'max_items': 100  
}
```

add_il_phone_numbers.json
```
[{'object': 'ILL000555': 'action': 'add_phone_number', 'value': '555-111-2222'},
{'object': 'ILL000556': 'action': 'add_phone_number', 'value': '555-333-3333'},
{'object': 'ILL000843': 'action': 'add_phone_number', 'value': '555-123-4567'},
]
```

etc.

The above are examples, format would likely vary as we determined our full use-case, and files wouldn't be intended to be written by hand.

We'd need to:
* build a tool that allowed for building a suggested change, presumably this would run online and let people look at what their proposed edit would do
* a MVP of this could save this output as a JSON file for them to submit, or we could get fancy and open a PR against the manual_data repository
* the tool would have to then allow users to paste in the proposed edit JSON and see the differences to review the change (again, a fancy version of this could integrate w/ GitHub)

Once an edit file is accepted, it would be run as part of the standard import process (or perhaps there'd be two types, a one-off edit and a recurring edit)- we'd then do away with our dependency on things like ``locked_fields`` (which are intended for manual editors) and simply re-apply the diff after a scrape.  It'd be important for there to be preconditions on most types of edits to ensure that we aren't overwriting good data w/ bad.  

Other things that'd be useful would be some sort of pruning tool that removes redundant/non-applicable JSON, but presumably that could wait until we saw real adoption.

**Comment by hulk-baba** [comment]
@jamesturk, the tracking of changes can be done via a distributed ledger a.k.a blockchain. Blockchain has been used to solve provenance of medicines/diamonds [everledger did this](https://www.everledger.io/). Similar things can also be employed to solve this problem, This can be a standalone project. I am currently working on solving provenance of medicine as my final year project. Please let me know your ideas on this one.

**Comment by jamesturk** [comment]
I don't think we'll be employing the blockchain for this one, a simpler log will suffice just fine

**Comment by In-vincible** [comment]
@jamesturk My last year's proposal was based on this description only, are we working on it this year?
