### ISSUE TITLE
future of notifications/alerts

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#18]
OpenStates.org used to integrate with Sunlight's Scout tool to provide email notifications, with Sunlight's login server and Scout gone we had to disable this feature, but it is far & away one of the most requested features.

We should explore what sorts of notifications/alerts people are most interested in, the simplest/cheapest path to provide them reliably, and what delivery mechanisms make the most sense.  Ideally I'd like to build this in a way where email was one output, that we most likely pay for/support, but in a way that people can build their own hooks in.  This is likely to materialize as part of the V2 API.

This is also written out in the [2017 Roadmap](https://github.com/openstates/meta/wiki/2017-Roadmap)

**Comment by johnnyman727** [comment]
Would love to have this feature. @jamesturk do you have an easily digestible bulleted list of action items that an eager contributor could get started with?

**Comment by jamesturk** [comment]
this work is going to be tackled in https://github.com/openstates/notifications
