### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#20]
let's automate things like crazy:

- [x] file issues when scrapers break 
- [x] run scrapers
- [x] backups
- [x] public data dumps
- [x] images
- [x] auto-close certain issues like failing scrapers
- [x] update automation to handle pupa & billy side-by-side

other ideas:

-  better QA on pull requests?  (use branch comparison script to run both and show differences?)
- file common data quality issues?

**Comment by In-vincible** [comment]
I want to apply for gsoc 2017 with open states please help me get started :)

**Comment by In-vincible** [comment]
@jamesturk do these ideas also comes under opencivic data tools?

**Comment by In-vincible** [comment]
@jamesturk do these ideas also comes under opencivic data tools?

**Comment by jamesturk** [comment]
I think there's always room to look at some of these things, but the basics listed above are done now.  Future enhancements will probably be discussed & introduced as new tickets
