### ISSUE TITLE
Open States API v2

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#21]
more to come, but this is where we'll plan the next iteration of the Open States API to be backed by Open Civic Data models

a few open questions:

- Open Civic Data data contains a lot more relationships than billy did, so intelligent "related resource" behavior would be useful
    - ocd-jsonapi repo has some work in this direction that uses the JSON API specification
    - GraphQL could also be incredibly powerful here, but we'd need to look at performance, etc.

- In addition to the basic list/get methods, what do we want to support?

- Do we want to support pre-2017 data? or should the new API start there?  it seems most users of older data would be better served by bulk data

- What is the deprecation timeline for the old API?
    - should be considerate w/r/t session timing.  if we're releasing in December 2017, let's let people get through 2018 session w/o switch.  probably fair to say that 2018 is last session for billy, possibly earlier if we get API out during 2017 sessions
    - need to look at usage, might be possible to shim common use cases & shorten deprecation timeline
    - one option: possibly seek financial support from those that depend upon it to pay for its continued survival?

**Comment by estaub** [comment]
I'd suggest getting strawman docs out way early, so folks can provide input.

Re **GraphQL**:  I'm working with/on a very full-featured GraphQL API based on the current API, with a Postgresql back end.  I don't need a lot of perf yet, so I'm just using a GraphQL schema+server autogen'd from the Postgres schema, using [PostgraphQL](https://github.com/calebmer/postgraphql).  The schema is pretty homely, but it has lots of performance-related features baked in, like intelligent joins, cursors and Relay Node Id support.  I haven't looked yet to see what kind of SQL it's generating.  It runs right out of the box; setup is as trivial as can be.  Even if you're not interested, kicking it off and fiddling with Graphiql will likely be profitable in requirement and design discovery.

If you decide to do a js-based GraphQL server, and PostgraphQL is not an option, consider use of [Join Monster](http://join-monster.readthedocs.io/en/latest/) to map from GraphQL to Postgresql.  I have no experience with it yet, but it smells right.  The main version is for the Facebook reference graphql-express implementation; there's also an Apollo flavor.

**Comment by jamesturk** [comment]
Thanks for the feedback on using GraphQL so far.  I think we'd probably use graphene since it fits our stack, and I'd be concerned about coupling it too closely to our internal schema but it's good to hear what's working elsewhere so we can take a look.

**Comment by jamesturk** [comment]
as mentioned in #1264 we should definitely link to OCD ids from legislator responses

**Comment by bjmc** [comment]
One thing that seems to be missing in the v1 API, that I'd like to see in v2 is the ability to search for bills with activity in the last `n` days. My understanding is that the `updated_since` search field only refers to the last time the Openstates scraper loaded data for that bill, not the last time there was a new `action` on a bill.

**Comment by jamesturk** [comment]
OK, in the interest of making these things a bit more actionable I've broken this out into the major things we need to plan. 

https://github.com/openstates/meta/projects/1

Feel free to file new issues
