### ISSUE TITLE
National level committee listing

### ISSUE THREAD

**Issue by ashavgtvm** [openstates/meta#36]
Hi ,
I am using the openstate API to list committees of different states.In that response , I could find a field as "level" and it holdsthe value "state".Does it mean whether the committee is state level or not ?
Is there any option to list the national level committees using the openstate API ? 

Thanks in advance.

**Comment by jamesturk** [comment]
We don't have national data in Open States, all of our data is state level.  For national committees you might try https://projects.propublica.org/api-docs/congress-api/#scope-of-data
