### ISSUE TITLE
2017 Q3/Q4 Plan

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#37]
Trying something new to communicate our general progress.  We'll aim to update this ticket on a regular basis w/ high-level updates on our progress.

2017 Q3 Priorities:

- [x] new Open Civic Data database
- [x] [API v2](https://github.com/openstates/meta/projects/1/)
- [x] [redo geo server (particularly w/ fix for FL)](https://github.com/openstates/openstates/issues/1218)
- [x] [GSoC Admin Tools](https://github.com/openstates/admintools)
- [ ] Light OpenStates.org Redesign

**Comment by jamesturk** [comment]
(we let this slip, but we'll do our best to be good at updating this ticket for the remainder of this quarter)

## 7/12 update

- new OCD database: 14/50 states loaded in as a test, turning on another 20 or so today

**Comment by mileswwatkins** [comment]
## 7/21 update

Hitesh:

- done: legislator retirement tool; data quality patch views; jurisdiction-specific person merge tool
- doing: name resolution tool; too-many or too-few people data quality checks

Miles:

- done: reviewed Hitesh's work; grant research
- doing: review Hitesh's work; pilot district map fix

**Comment by mileswwatkins** [comment]
## 7/27 update

Hitesh:

- done: add too-many-people and too-few-people data quality issues; name resolution tool
- doing: UX changes with @jamesturk; status-update blog post; considering public view of data quality issues

Miles:

- done: review Hitesh's work; alpha for replacing OS.org district maps
- doing: review Hitesh's work; release OS.org district map fix

**Comment by todrobbins** [comment]
Nice work everyone! Which jurisdictions are not importing?

**Comment by jamesturk** [comment]
- [ ] CA: various ongoing issues w/ pupa entity resolution (WIP)
- [ ] MA: ongoing VoteEvent issues (fix hopefully in place for next run)
- [ ] OH: scraper is broken due to source changes (needs a fix)

**Comment by mileswwatkins** [comment]
## 8/9 Update

Hitesh:

- done: closed out all PRs
- doing: data quality exceptions, documentation

Miles:

- done: away on vacation
- doing: district maps (maybe 8 hours of work left before they're in production)

James:

- done: Stripe widget research
- doing: Stripe widget implementation

**Comment by mileswwatkins** [comment]
## 8/16 update

Hitesh:

- done: bugfixes, issue-ignoring tool
- doing: admintools documentation

Miles:

- done: district maps
- doing: district-matching debug, deployment of maps to front-end

James:

- done: Stripe widget beta
- doing: API v2 and build pipeline exploration

**Comment by mileswwatkins** [comment]
## 8/23 update

Hitesh:

- done: bugfixes, documentation
- doing: documentation, wrapping-up blog post

Miles:

- done: maps are live once more
- doing: maps improvements, other site tweaks, maybe other geo stuff

**Comment by mileswwatkins** [comment]
## 8/29 update

Hitesh:

- done: documentation, blog post

Miles:

- doing: map improvements

**Comment by mileswwatkins** [comment]
## 9/13 update

Miles:

- done and doing: user research

James:

- done and doing: administrative tasks and outreach

**Comment by jamesturk** [comment]
Redesign is pushed to 2018 and geoserver is coming in January
