### ISSUE TITLE
Response for preflight is invalid

### ISSUE THREAD

**Issue by suspense304** [openstates/meta#39]
https://www.openstates.org/api/v1/legislators/geo/?lat=38.3242015&long=-81.5661657: Response for preflight is invalid (redirect)

  $.ajax({
    url: "https://www.openstates.org/api/v1/legislators/geo/?lat=" + lat + "&long=" + lng,
    type: "GET",
    dataType: 'json',
    headers: {'X-API-Key': 'KEY HERE'},
    success: function(data)
    {
      console.log(data);
    }
  });

I'm guessing the url I'm using is incorrect but it's the one that matches the documentation. I've tried http as well. I've left out the www also. Nothing has corrected this error.

**Comment by jamesturk** [comment]
dealt w/ via email - was cross site error (was sending OPTIONS request & getting a 405)
