### ISSUE TITLE
2018 Proposals

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#40]
I want to propose a few changes to Open States for 2018.

At the moment all of these are open to discussion, we'll "announce" these more formally once they've been agreed upon closer to the end of the year.

1) 2018 will see the introduction of API v2 and a new OpenStates.org.  Our current thinking is that these will have 2017 data onward, but will not have data going back to 2009.  We will of course make bulk data available for all old sessions currently supported available indefinitely.  Given the limited API/site usage of old data it doesn't seem worth the cost/effort to bring the actual data over.

2) API v1 will exist until ~Jan 1st 2019.  (This of course presumes a early 2018 release of API v2 is on track)

3) Events will be formally deprecated.  They will not appear on OpenStates.org nor in API v2.  We will stop scraping them in the states that still have them.  Based on usage they are essentially impossible to justify at this point.  We'll probably let the scrapers continue to exist in our repo for a while, TBD.

4) Issues that only exist in API v1 will generally not be fixed.  The new data model is way better/way easier to work with- and support for API v1 is mainly so people have time to migrate, v2 *will* have better data and users will be urged to migrate to it for the best data.

This list isn't yet complete or final, but we want to announce these things well in advance so that objections/concerns can be raised.  Doing these things will streamline how we work and let us tackle a bunch of the backlog during next year.  It is likely that 2018 will be a year of transition, but we're timing all this to get things in great shape so that the next set of major sessions (2019) can go as smoothly as possible for us and API users alike.

**Comment by estaub** [comment]
It might save churn (calendar time till stable) if there's an early API spec or examples or similar to review.  If the input to the pupa-to-billy scrape phase (which I haven't looked at yet) is the intended schema, that would be great to know.

**Comment by jamesturk** [comment]
The schema will indeed be the OCD specification (which more or less matches
the input to the pupa2billy step modulo some implementation details)

https://opencivicdata.readthedocs.io/en/latest/proposals/0003.html OCDEP
3-7 document the format, and the models etc. at
https://github.com/opencivicdata/python-opencivicdata/tree/master/opencivicdata/legislative/models
might be helpful too.

The actual API format will be based on these, but agreed that the sooner we
can get an alpha out the better.

**Comment by jamesturk** [comment]
https://blog.openstates.org/open-states-in-2018-and-beyond-d35f1717982b
