### ISSUE TITLE
API v2 - correlation between OCD ID's and OpenStates ID's

### ISSUE THREAD

**Issue by estaub** [openstates/meta#41]
Where people migrating apps from API V1 to V2 have any data of their own associated with legislative entities, they will need to correlate entities from one to the other.

Once the v2 API is up, it may make sense to do one or both of:

* optionally include the OS ID with OCD entities retrieved via API V2.  
When the V1 API is shut off, no new OS IDs would be generated, but old OS IDs would continue to be available for a year or so.
* include the OCD ID in data retrieved from the current API

I think the first option may be more significant, in that it may allow shutting off the V1 API sooner.  I'm guessing a lot about the nature of other folks' apps and timetables, though.

**Comment by jamesturk** [comment]
OS person Ids are now available in API v2 in the identifiers data 👍
