### ISSUE TITLE
API V2 needs: >updatedAt query, votes

### ISSUE THREAD

**Issue by estaub** [openstates/meta#43]
Great to see the progress!

A couple of things I just want to make sure are in the hopper:

- querying for entities updated **since** &lt;date-time>.  This doesn't fit the query-by-example paradigm used for most fields.  FWIW, I've seen two approaches for this: one is to add e.g. an `updatedSince` query parameter, and the other is to, mongo-style, accept an object as the `updatedAt` value, like `{ge: "some date"}`.  From what I can tell, the `updatedSince` approach is more common, but the Mongo-style approach probably scales better in the implementation.  I believe the GraphQL union will support the "string or comparison-object" type needed.

- votes, and especially roll-calls.  If you need a tighter representation for roll-call data, I have something to offer.

**Comment by jamesturk** [comment]
updatedSince is available on bills docs.openstates.org/en/latest/api/v2/root-nodes.html#id1

We should add it on people and maybe elsewhere, what did you have in mind?

we also have votes under bills, were you thinking something else?

**Comment by estaub** [comment]
Mostly, I have to plead blindness!  I'm not sure how I missed so much.  

Yes, I happened to look for updatedSince on people.  I think it's deferrable there, though.  

Folks have asked for votes under legis, fwiw.  

I'm a little worried about the size of roll-calls in this format.

**Comment by jamesturk** [comment]
Opened openstates/new-openstates.org#16 for votes under legislators and openstates/new-openstates.org/#17 for updatedSince elsewhere

What sort of concern about the size of roll calls?

**Comment by jamesturk** [comment]
updatedSince is now avilable on people too, going to close this one but feel free to open related issues on the API v2 repo
