### ISSUE TITLE
Consideration of Forward-Porting Options

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#44]
As we approach the time to make the transition from API v1 (& old infrastructure) to API v2 (& new infrastructure) there are a few pressing questions that have an impact on how we go forward from here.

1) How far back will we preserve data?  (we've said we intend to at least bring over current sessions)
2) How will we preserve Open States IDs?  (we've said we intend to do so)
3) How long will we support API v1?  (we've said we'll do so through the end of the year)
4) Where will manual data fixes be made? (unclear)

There are a few paths by which we can accomplish this:

**Plan A**
- Pupa becomes system of record.  pupa2billy keeps old DB up to date from pupa DB directly
- 1) We scrape current session data into pupa and don't have any historical data ported over.
- 2) We'd have to resolve OS vs. OCD IDs, which we could do using a script that matched unambiguous ones (bill w/ session,chamber,bill_id match or person w/ party,state,role,name match, etc.)
- 3) API v1 would be supported until we turn off pupa2billy
- 4) data fixes would be made in pupa and pushed back to billy

Pros: shortest path to dropping old stuff, pupa as SOR means API v2/new site have best possible data
Cons: hesitation around new DQ tools maturity, need to write OS->OCD ID resolver tool

**Plan B**
- Billy remains system of record.  We start running a billy2pupa to get data quality fixes moved over.
- 1) We could bring over as much/little historical data as we want.  Would likely introduce a bunch of old/broken data to pupa though.
- 2) We could just push OS IDs into the OCD db via the billy2pupa process.
- 3) API v1 supported easily since billy is system of record
- 4) data fixes would be made in billy and ported forward via billy2pupa process

Pros: can keep historical data easily, keep using old tools longer
Cons: have to write/maintain billy2pupa, billy as SOR is limiting, rougher data ported to new DB, we'd no longer be doing a direct to pupa import which would mean missing a ton of error handling at scrape time (I suppose we could keep this on for error checking, but throw it out?)

**Plan C** 
- Essentially dual systems of record.  pupa2billy runs when it currently does and we make updates in both admins for a while

- 1) same as Plan A
- 2) same as Plan A
- 3) same as Plan B but maybe billy DB would lag eventually
- 4) data fixes made in both places

Pros: path of least resistance, status quo essentially
Cons: 2x data quality fixes, DBs would drift further and further out of sync, still need to write billy->pupa ID sync tool

I think the choice is essentially between A and B.  C seems untenable.

Implementation for A:
- modify pupa2billy to start running against DB instead of JSON
- start using new DQ tools for retirements, contact detail fixes, merges
- add OS->OCD ID tool for bill & legislator IDs
- when done w/ billy/API v1: turn off pupa2billy and OS->OCD ID scripts and 💥 

Implementation for B:
- write & test billy2pupa 
- stop importing directly into pupa (run w/ --scrape only)
- when done w/ billy/API v1: migrate to new DQ tools, turn off billy2pupa, start running w/ --import again

**Comment by mileswwatkins** [comment]
Yeah, I think I agree that A is the best plan. I mean, it's what we've been aiming for all along, and we have to get there at some point! Let's talk about timeline at our next meeting.

**Comment by jamesturk** [comment]
Updating this w/ more current answers:

- How far back will we preserve data? (we've said we intend to at least bring over current sessions)

OCD db has latest data and data is being backported to v1 until we shut it off

- How will we preserve Open States IDs? (we've said we intend to do so)

We're doing this via the people repo now, and we'll make no guarantees for non-person IDs (committees & events were ephemeral, bills & votes have a better reference mechanism)

- How long will we support API v1? (we've said we'll do so through the end of the year)

Still a bit unclear, but looking at options to accelerate this now.

- Where will manual data fixes be made? (unclear)

The people repo pretty much solved this.


So we're really just left w/ a deprecation timeline for v1 (or running v1 endpoints off OCD db somehow)

**Comment by jamesturk** [comment]
https://beta.openstates.org/api/v1 is live, closing this one at last
