### ISSUE TITLE
Organize early-2017 hackathon

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/meta#9]
As mentioned in our blog posts, we're aiming to have a hackathon in early 2017. I'll work on organizing this for now. Main questions:

- Hosting: Where and when?
  - Would be nice to connect with an existing meetup, such as Code for DC
  - Could also host independently, such as at a downtown DC office of an allied organization
  - @jamesturk and I are both in DC for much of January, so most dates are on the table. Weekend may probably be best if we host outside of an existing meetup.
- Publicity: How do we get the most people interested?
  - Outreach to all previous committers to OS
  - Contact users of the data
  - Outreach to the public via social media
- What to focus the work on?
  - At that point, it'll probably be best to focus on Billy-to-Pupa rewrites
  - Potential chats surrounding optimization of different bits of infrastructure

**Comment by mileswwatkins** [comment]
Update for now: have been talking with Code for DCers, and it seems like that's a good possibility. We'll be planning logistics in the week or two following Christmas, hopefully aiming for February for the event. It was also suggested that we cross-promote or partner the hackathon with other groups, such as DC Legal Hackers.

**Comment by jalbertbowden** [comment]
lmk if i can help

**Comment by mileswwatkins** [comment]
Updating: we're still in chats with Code for DC, @jamesturk and/or I will be speaking with them in-person at their next meetup. Hopefully will have details from there.

**Comment by todrobbins** [comment]
I'm a Utahan and was wondering if our state's scraper/etc needs any love? Cheers!

**Comment by mileswwatkins** [comment]
Hi @todrobbins! If you hop on the Open States Slack, we can chat about next steps for the Utah scraper. Just sent you an invite to your GH-listed email address.

**Comment by mileswwatkins** [comment]
We're tentatively scheduling this for Saturday, April 1. More information forthcoming once we determine hosting location! Stay tuned here and on the Slack.

**Comment by jamesturk** [comment]
We're now planning this for Sunday March 19th.  More to come.

**Comment by mileswwatkins** [comment]
Organized! https://blog.openstates.org/post/march-2017-dc-code-sprint/

Closing this ticket, as additional updates will be released via the blog and/or [EventBrite notifications](http://www.eventbrite.com/e/open-states-code-sprint-registration-32159601233?ref=ebtnebregn).
